### ISSUE TITLE
Leste - crash on importing python location module

### ISSUE THREAD

**Issue by sicelo** [maemo-leste-extras/pyfuelpad#3]
I installed pyfuelpad and it keeps crashing while trying to load the `location` module.

@javiplx how are you overcoming this in your install? For the time being, I removed `location` from https://github.com/maemo-leste-extras/pyfuelpad/blob/master/fuelpad/db.py#L118

**Comment by javiplx** [comment]
I thought I left that fixed. Your approach will likely cause an exception if adding a record, although I've no idea what could actually happen in this scenario.
An empty `location.py` somewhere in Python search path is better approach (is the one I did use to develop)

**Comment by javiplx** [comment]
If running jobs on jenkins is enough, the fix should be available.

**Comment by sicelo** [comment]
I can confirm that the latest update fixes the issue.
>Your approach will likely cause an exception if adding a record, although I've no idea what could actually happen in this scenario

Actually it didn't have any bad side effects in my testing. I was able to add records just fine.

**Comment by MerlijnWajer** [comment]
FWIW current leste-devel has python-location and liblocation, we're still working out some kinks, but this should all be resolved soon.
